# Threshhold 0 bei Beispiel Streckensperrung (20 Durchgänge)

t0_d0 = [False, True, True, True, True, True, True, True, True, True, True, True, True, True, True]
t0_d1 = [False, True, True, True, True, True, True, True, True, True, True, True, True, True, True]
t0_d2 = [False, True, True, True, True, True, True, True, True, True, True, True, True, True, True]
t0_d3 = [False, True, True, True, True, True, True, True, True, True, True, True, True, True, True]
t0_d4 = [False, True, True, True, True, True, True, True, True, True, True, True, True, True, True]
t0_d5 = [False, True, True, True, True, True, True, True, True, True, True, True, True, True, True]
t0_d6 = [False, True, True, True, True, True, True, True, True, True, True, True, True, True, True]
t0_d7 = [False, True, True, True, True, True, True, True, True, True, True, True, True, True, True]
t0_d8 = [False, True, True, True, True, True, True, True, True, True, True, True, True, True, True]
t0_d9 = [False, True, True, True, True, True, True, True, True, True, True, True, True, True, True]
t0_d10 = [False, True, True, True, True, True, True, True, True, True, True, True, True, True, True]
t0_d11 = [False, True, True, True, True, True, True, True, True, True, True, True, True, True, True]
t0_d12 = [False, True, True, True, True, True, True, True, True, True, True, True, True, True, True]
t0_d13 = [False, True, True, True, True, True, True, True, True, True, True, True, True, True, True]
t0_d14 = [False, True, True, True, True, True, True, True, True, True, True, True, True, True, True]
t0_d15 = [False, True, True, True, True, True, True, True, True, True, True, True, True, True, True]
t0_d16 = [False, True, True, True, True, True, True, True, True, True, True, True, True, True, True]
t0_d17 = [False, True, True, True, True, True, True, True, True, True, True, True, True, True, True]
t0_d18 = [False, True, True, True, True, True, True, True, True, True, True, True, True, True, True]
t0_d19 = [False, False, True, True, True, True, True, True, True, True, True, True, True, True, True]

# Threshhold 10 bei Beispiel Streckensperrung (20 Durchgänge)

t10_d0 = [False, False, False, False, False, True, True, True, True, True, True, True, True, True, True]
t10_d1 = [False, False, False, False, True, False, True, True, True, True, True, True, True, True, True]
t10_d2 = [False, False, False, False, True, True, True, True, True, True, True, True, True, True, True]
t10_d3 = [False, False, False, False, False, True, True, True, True, True, True, True, True, True, True]
t10_d4 = [False, False, False, False, False, True, False, True, True, True, True, True, True, True, True]
t10_d5 = [False, False, False, False, True, False, True, True, True, True, True, True, True, True, True]
t10_d6 = [False, False, False, False, True, True, True, True, True, True, True, True, True, True, True]
t10_d7 = [False, False, False, False, False, True, True, True, True, True, True, True, True, True, True]
t10_d8 = [False, False, False, False, False, False, True, True, True, True, True, True, True, True, True]
t10_d9 = [False, False, False, False, True, False, True, True, True, True, True, True, True, True, True]
t10_d10 = [False, False, False, False, False, True, True, True, True, True, True, True, True, True, True]
t10_d11 = [False, False, True, False, True, True, True, True, True, True, True, True, True, True, True]
t10_d12 = [False, False, False, False, True, True, True, True, True, True, True, True, True, True, True]
t10_d13 = [False, False, False, False, True, False, True, True, True, True, True, True, True, True, True]
t10_d14 = [False, False, False, False, False, False, True, True, True, True, True, True, True, True, True]
t10_d15 = [False, False, False, False, True, False, True, True, True, True, True, True, True, True, True]
t10_d16 = [False, False, False, False, False, False, True, True, True, True, True, True, True, True, True]
t10_d17 = [False, False, False, False, True, True, True, True, True, True, True, True, True, True, True]
t10_d18 = [False, False, False, False, False, False, False, True, True, True, True, True, True, True, True]
t10_d19 = [False, False, False, False, False, True, True, True, True, True, True, True, True, True, True]
